defmodule Helpdesk.Repo.TenantMigrations.AddTicketsAndRepresentatives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false, prefix: prefix()) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:subject, :text)
    end
  end

  def down do
    drop(table(:tickets, prefix: prefix()))
  end
end
